# Generated by Django 3.0.3 on 2020-03-09 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('position', models.IntegerField(blank=True, null=True, verbose_name='Position')),
                ('level', models.IntegerField(blank=True, null=True)),
                ('named_url', models.CharField(default=None, max_length=50, null=True, unique=True)),
                ('left', models.IntegerField(blank=True, null=True)),
                ('right', models.IntegerField(blank=True, null=True)),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app_menu.Category', verbose_name='Parent category')),
            ],
            options={
                'ordering': ('left',),
            },
        ),
    ]
